### PR TITLE
Fix okta_app_* unable to import authentication policy

### LINKED ISSUE #1742: UnPlanned changes - `okta_app*` - unexpected `authentication_policy`
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)
- okta_app*

### Terraform Configuration Files

```hcl
resource "okta_app_bookmark" "example" {
  label  = "Example"
  url    = "https://example.com"
}
```

### Expected Behavior

`Terraform Plan` should outline all changes that would result from executing `Terraform Apply` 

### Actual Behavior

When the upstream API chooses default behavior we don't expose this in the `Terraform Plan`

In this case the existing well known behavior is that omitting `authentication_policy` on `okta_app*` resources results in the default authentication policy being used
This can unexpectedly replace a authentication policy that was click-ops provisioned to an application

I believe this has something to do with this API not supporting partial updates and assuming that an omitted value is equivalent to a null value

### Steps to Reproduce

1. `terraform apply`
2. Click-Ops change Auth Policy
3. `terraform apply`
4. Auth Policy has now changed in a way that was not visible to IAC

### Important Factoids

Most of our engineers expect that `Terraform Plan` will outline all changes that would result from executing `Terraform Apply` 
When this contract is broken, it understandably catches most engineers unaware and can cause outages

One of the benefits of Terraform is that it can be rolled out gradually because it does not attempt to modify resources that are not under management
But in this case this is being undermined by default behaviors in the upstream API

Some ideas below for paths forward to more intuitive behavior
Things within Okta Terraform's control
 - Surface what will happen in the `Terraform plan` by manually constructing plan info (not sure if this is possible)
 - Require the attribute on `okta_app*` resources
   - support `"default"` as a string
   - require using the ID from a Data Source

Things outside the Okta TF provider's control
 - Raise an issue upstream team that owns the API
   - support partial updates on the API in question (all fields)
   - leave authentication policy unchanged if it was omitted
   - question why omitted is treated as equivalent to `null` (requiring explicit null-ish values on endpoints that don't support partial updates seems like less of a footgun imo)

### LINKED ISSUE #1942: okta_app_bookmark import missing authentication_policy
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```shell
% terraform -v
Terraform v1.7.5
on darwin_arm64
```

### Affected Resource(s)

- okta_app_bookmark

### Terraform Configuration Files

```hcl
terraform {
  backend "local" {
    path = "terraform.tfstate"
  }
  required_providers {
    okta = {
      source = "okta/okta"
      version = "4.8.0"
    }
  }
}

provider "okta" {}

resource "okta_app_bookmark" "example" {
  label  = "Terraform Test"
  url    = "https://example.com"
  authentication_policy = "12345"
}
```

### Debug Output

```shell
terraform init
terraform plan
# Shows it is going to add the app which is correct (as it has not been imported yet)
terraform import okta_app_bookmark.example abcde
terraform plan
# Now shows it is going to set the authentication policy which should have been imported
```

Plan Output
```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  ~ update in-place

Terraform will perform the following actions:

  # okta_app_bookmark.example will be updated in-place
  ~ resource "okta_app_bookmark" "example" {
      + authentication_policy      = "12345"
        id                         = "abcde"
        name                       = "bookmark"
        # (11 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

### Panic Output
n.a.

### Expected Behavior
Terraform app was imported so it should not be making any changes to the authentication policy. In the Okta Admin the authentication_policy is set to the same value as in the Terraform configuration so no changes should be on the Terraform plan output (after import).

#### Can this be done in the Admin UI?

n.a.

#### Can this be done in the actual API call?

n.a.

### Actual Behavior

(see above)

### Steps to Reproduce

(see above)

### Important Factoids

n.a.

### References

* I have tried to raise this with Okta Support Case: 02017270

### Notes

* I suspect this is the same for other applications (but I have not checked)

### PR DESCRIPTION
**Pull request by duytiennguyen-okta**
Close #1942 
Close #1742

### CODE REVIEW

File: okta/resource_okta_app_bookmark.go [hunk 1]
```diff
@@ -40,6 +40,7 @@ other arguments that changed will be applied.`,
 			"authentication_policy": {
 				Type:        schema.TypeString,
 				Optional:    true,
+				Computed:    true,
```
Comment (exitcode0) [inline okta/resource_okta_app_bookmark.go:43]: I don't have confidence in my knowledge of TF provider schemas and their behaviours

Will setting `Computed: true` here prevent the user from specifying or updating the  authentication policy on a given `okta_app_*`?

Comment (duytiennguyen-okta) [reply okta/resource_okta_app_bookmark.go:43]: No. It will allow the provider to set the authentication_policy to default if it is not specified. I want to deprecate authentication_policy, but it will have to be major version change

**Review by monde — APPROVED** [review]
