### PR TITLE
OKTA-1073592 | Adding Support For custom_app Authenticator

### LINKED ISSUE #2407: okta_authenticator - cannot create a custom push authenticator
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
        Before submitting a bug report, we ask that you first [search existing issues](https://github.com/okta/terraform-provider-okta/issues) and [pull requests](https://github.com/okta/terraform-provider-okta/pulls) to see if someone else may have experienced the same issue or may have already submitted a fix for it. This helps to keep all relevant information in one place, including any potential workarounds.

### A Note on Terraform Core Issues

We also ask that you consider whether your issue may be related to Terraform Core. If you are running into one of the following scenarios, we recommend [opening an issue](https://github.com/hashicorp/terraform/issues/new/choose) in the Terraform Core repository instead:

* [Configuration Language](https://developer.hashicorp.com/terraform/language) or resource ordering issues
* [State](https://developer.hashicorp.com/terraform/language/state) and [State Backend](https://developer.hashicorp.com/terraform/language/backend) issues
* [Provisioner](https://developer.hashicorp.com/terraform/language/resources/provisioners/syntax) issues
* [Registry](https://registry.terraform.io/) issues
* Issues that span resources across multiple providers

### Terraform Version & Okta Provider Version(s)

Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/providers/okta/okta/ v5.1.0

### Affected Resource(s)

okta_authenticator

### Can this be done in the Admin UI?

Yes

### Can this be done in the actual API call?

Yes

### Customer Information

Organization Name: demo-gray-hawk-94326
Paid Customer: yes

### Terraform Configuration

```tf
resource "okta_app_oauth" "pushauthenticator" {
  type  = "native"
  label = "Authenticator App"
  grant_types = [
    "authorization_code",
    "urn:ietf:params:oauth:grant-type:jwt-bearer"
  ]
  consent_method             = "REQUIRED"
  issuer_mode                = "DYNAMIC"
  token_endpoint_auth_method = "none"
  post_logout_redirect_uris = [
    "com.okta.example:/callback:/"
  ]
  redirect_uris = [
    "com.okta.example:/callback"
  ]
  implicit_assignment = true
  pkce_required       = true
}
resource "okta_app_oauth_api_scope" "pushauthenticator" {
  app_id = okta_app_oauth.ciba.id
  issuer = "https://demo-gray-hawk-94326.okta.com"
  scopes = [
    "okta.myAccount.appAuthenticator.manage",
    "okta.myAccount.appAuthenticator.read"
  ]
}
resource "okta_authenticator" "push" {
  name               = "Okta Push Authenticator"
  key                = "custom_app"
  status             = "ACTIVE"
  legacy_ignore_name = false
  settings = jsonencode(
    {
      userVerification = "PREFERRED"
      appInstanceId    = okta_app_oauth.pushauthenticator.id
    }
  )
  provider_json = "{\"type\":\"PUSH\",\"configuration\":{\"fcm\":\"xxxxxxx\"}}"
}
```

### Debug Output

2025-07-17T12:27:53.629+1000 [DEBUG] provider.terraform-provider-okta: {
2025-07-17T12:27:53.629+1000 [DEBUG] provider.terraform-provider-okta:  "id": "autt9x2hskVl69Clz697",
2025-07-17T12:27:53.629+1000 [DEBUG] provider.terraform-provider-okta:  "key": "custom_app",
2025-07-17T12:27:53.629+1000 [DEBUG] provider.terraform-provider-okta:  "name": "Okta Push Authenticator",
2025-07-17T12:27:53.629+1000 [DEBUG] provider.terraform-provider-okta:  "provider": {
2025-07-17T12:27:53.629+1000 [DEBUG] provider.terraform-provider-okta:   "configuration": {},
2025-07-17T12:27:53.629+1000 [DEBUG] provider.terraform-provider-okta:   "type": "PUSH"
2025-07-17T12:27:53.629+1000 [DEBUG] provider.terraform-provider-okta:  },
2025-07-17T12:27:53.629+1000 [DEBUG] provider.terraform-provider-okta:  "settings": {
2025-07-17T12:27:53.629+1000 [DEBUG] provider.terraform-provider-okta:   "appInstanceId": "0oat9x2kl5zDd61AJ697",
2025-07-17T12:27:53.629+1000 [DEBUG] provider.terraform-provider-okta:   "userVerification": "PREFERRED"
2025-07-17T12:27:53.629+1000 [DEBUG] provider.terraform-provider-okta:  },
2025-07-17T12:27:53.629+1000 [DEBUG] provider.terraform-provider-okta:  "type": "app"
2025-07-17T12:27:53.629+1000 [DEBUG] provider.terraform-provider-okta: }
2025-07-17T12:27:54.068+1000 [DEBUG] provider.terraform-provider-okta: {
2025-07-17T12:27:54.068+1000 [DEBUG] provider.terraform-provider-okta:  "errorCode": "E0000001",
2025-07-17T12:27:54.068+1000 [DEBUG] provider.terraform-provider-okta:  "errorSummary": "Api validation failed: provider.configuration.apns",
2025-07-17T12:27:54.068+1000 [DEBUG] provider.terraform-provider-okta:  "errorLink": "E0000001",
2025-07-17T12:27:54.068+1000 [DEBUG] provider.terraform-provider-okta:  "errorId": "oaex9YWXI57Q6etfiq3avzRrw",
2025-07-17T12:27:54.068+1000 [DEBUG] provider.terraform-provider-okta:  "errorCauses": [
2025-07-17T12:27:54.068+1000 [DEBUG] provider.terraform-provider-okta:   {
2025-07-17T12:27:54.068+1000 [DEBUG] provider.terraform-provider-okta:    "errorSummary": "provider.configuration.apns: The field cannot be left blank"
2025-07-17T12:27:54.068+1000 [DEBUG] provider.terraform-provider-okta:   },
2025-07-17T12:27:54.068+1000 [DEBUG] provider.terraform-provider-okta:   {
2025-07-17T12:27:54.068+1000 [DEBUG] provider.terraform-provider-okta:    "errorSummary": "provider.configuration.fcm: The field cannot be left blank"
2025-07-17T12:27:54.068+1000 [DEBUG] provider.terraform-provider-okta:   }
2025-07-17T12:27:54.068+1000 [DEBUG] provider.terraform-provider-okta:  ]
2025-07-17T12:27:54.068+1000 [DEBUG] provider.terraform-provider-okta: }

### Expected Behavior

`provider.configuration` should contain `:{"fcm":"xxxxxxx"}

### Actual Behavior

`provider.configuration` should contains `:{}

### Steps to reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

N/A

### PR DESCRIPTION
**Pull request by dhiwakar-okta**
Fixes #2407
Added support for managing Custom App type authenticators.
Recorded new VCR tests for the same reason.

### CODE REVIEW

File: sdk/v2_authenticatorProviderConfigurationUserNamePlate.go [hunk 1]
```diff
@@ -4,3 +4,15 @@ package sdk
 type AuthenticatorProviderConfigurationUserNamePlate struct {
 	Template string `json:"template,omitempty"`
 }
+
+// Apple Push Notification Service
+type APNS struct {
```
Comment (aditya-okta) [inline sdk/v2_authenticatorProviderConfigurationUserNamePlate.go:9]: From where did we get these configs?

File: okta/services/idaas/resource_okta_authenticator.go [hunk 2]
```diff
@@ -22,6 +22,18 @@ func resourceAuthenticator() *schema.Resource {
 		Importer: &schema.ResourceImporter{
 			StateContext: schema.ImportStatePassthroughContext,
 		},
+		ValidateRawResourceConfigFuncs: []schema.ValidateRawResourceConfigFunc{
```
Comment (aditya-okta) [inline okta/services/idaas/resource_okta_authenticator.go:25]: Why do we need this?

**Review by aditya-okta — APPROVED** [review]
approved with comments

File: sdk/v2_authenticatorProviderConfigurationUserNamePlate.go (hunk 1 above)
Comment (dhiwakar-okta) [reply sdk/v2_authenticatorProviderConfigurationUserNamePlate.go:9]: I had to create them for the custom_app type authenticator since they were missing from the internal SDK, you can refer to [this link](https://developer.okta.com/docs/api/openapi/okta-management/management/tag/Authenticator/#tag/Authenticator/operation/createAuthenticator)

I've included a screenshot for your reference.

File: okta/services/idaas/resource_okta_authenticator.go (hunk 2 above)
Comment (dhiwakar-okta) [reply okta/services/idaas/resource_okta_authenticator.go:25]: Basically `legacy_ignore_name` does not treat changes in name as actual changes to the authenticator.
For most of the existing authenticator types, there can only really ever be 1 instance. 
For custom_app type authenticators however, we can have more than 1 instance so we need to pass in a name and ensure that all renames are applied properly.

Basically, this validation function is basically saying 

```
if the key==custom_app 
    then legacy_ignore_name MUST be false 
else
    raise an error
```
