### PR TITLE
Okta 920842 detect change in orn path

### LINKED ISSUE #1991: `okta_resource_set` always detects a change in resources with an ORN path
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.8.2
on linux_amd64
+ provider registry.terraform.io/okta/okta v4.8.1
```

### Affected Resource(s)

- okta_resource_set

### Terraform Configuration Files

I've redacted the organisation ID below, but it's reproduceable in every environment I've tried so far. All 3 are classic engine environments.
```hcl
resource "okta_resource_set" "all_customizations" {
  label = "Brand Customizations"
  description = "Brand Customizations"
  resources = [
    "orn:oktapreview:idp:00xxxxxxxx0h7:customizations"
  ]
}
```

### Expected Behavior
The resource set should be created once and then not appear in the terraform plan until the configuration changes (or drifts on the tenant)

### Actual Behavior
Terraform persistently detects that a change is required and attempts to add the resource again on every plan and apply. Subsequent applies still succeed.

```
  # okta_resource_set.all_customizations will be updated in-place
  ~ resource "okta_resource_set" "all_customizations" {
        id          = "iam22okfx9urzNXZE0h8"
      ~ resources   = [
          + "orn:oktapreview:idp:00xxxxxxxx0h7:customizations",
        ]
        # (2 unchanged attributes hidden)
    }
```

### Steps to Reproduce
1. Insert config block above to your main.tf
2. Run `terraform plan` and `terraform apply` to create the resource set
3. Run `terraform plan` again and see that the resource_set will be updated in the plan

### PR DESCRIPTION
**Pull request by aditya-okta**
Closes #1991 , #2224 , #1504 
Added a new argument called **resources_orn** to the **okta_resource_set** to allow managing resources via orn as well.

### CODE REVIEW

**Comment by exitcode0** [comment]
This is potentially a duplicate / related to #2224

File: okta/provider_test.go [hunk 1]
```diff
@@ -96,7 +96,7 @@ func TestMain(m *testing.M) {
 	// TF_VAR_hostname allows the real hostname to be scripted into the config tests
 	// see examples/okta_resource_set/basic.tf
 	os.Setenv("TF_VAR_hostname", fmt.Sprintf("%s.%s", os.Getenv("OKTA_ORG_NAME"), os.Getenv("OKTA_BASE_URL")))
-
+	os.Setenv("TF_VAR_orgId", os.Getenv("OKTA_ORG_ID"))
```
Comment (pranav-okta) [inline okta/provider_test.go]:
```suggestion
	os.Setenv("TF_VAR_orgID", os.Getenv("OKTA_ORG_ID"))
```

**Comment by aditya-okta** [comment]
@exitcode0 , you are right, in #2224, the root cause is the same as what we are fixing here

File: okta/provider_test.go (hunk 1 above)
Comment (pranav-okta) [inline okta/provider_test.go]:
```suggestion
	os.Setenv("TF_VAR_orgID", os.Getenv("OKTA_ORG_ID"))
```

File: okta/resource_okta_resource_set_test.go [hunk 2]
```diff
@@ -186,6 +186,43 @@ resource "okta_resource_set" "test" {
...
+		PreCheck:          testAccPreCheck(t),
+		ErrorCheck:        testAccErrorChecks(t),
+		CheckDestroy:      nil,
+		ProviderFactories: testAccProvidersFactories,
+		Steps: []resource.TestStep{
+			{
+				Config: mgr.ConfigReplace(fmt.Sprintf("%s\n%s", baseConfig, step1Config)),
+				Check: resource.ComposeTestCheckFunc(
+					resource.TestCheckResourceAttr(resourceName, "resources_orn.#", "2"),
+					resource.TestCheckResourceAttr(resourceName, "resources_orn.0", fmt.Sprintf("orn:okta:directory:%s:groups", os.Getenv("TF_VAR_orgId"))),
```
Comment (pranav-okta) [inline okta/resource_okta_resource_set_test.go]:
```suggestion
					resource.TestCheckResourceAttr(resourceName, "resources_orn.0", fmt.Sprintf("orn:okta:directory:%s:groups", os.Getenv("TF_VAR_orgID"))),
```

File: okta/resource_okta_resource_set_test.go [hunk 3]
```diff
@@ -186,6 +186,43 @@ resource "okta_resource_set" "test" {
...
+					resource.TestCheckResourceAttr(resourceName, "resources_orn.1", fmt.Sprintf("orn:okta:directory:%s:users", os.Getenv("TF_VAR_orgId"))),
```
Comment (pranav-okta) [inline okta/resource_okta_resource_set_test.go]:
```suggestion
					resource.TestCheckResourceAttr(resourceName, "resources_orn.1", fmt.Sprintf("orn:okta:directory:%s:users", os.Getenv("TF_VAR_orgID"))),
```

File: okta/resource_okta_resource_set.go [hunk 4]
```diff
@@ -79,10 +89,16 @@ func resourceResourceSetRead(ctx context.Context, d *schema.ResourceData, meta i
...
-	_ = d.Set("resources", flattenResourceSetResources(resources))
+	if _, ok := d.GetOk("resources"); ok {
+		_ = d.Set("resources", flattenResourceSetResourcesLinks(resources))
+	} else if _, ok := d.GetOk("resources_orn"); ok {
+		_ = d.Set("resources_orn", flattenResourceSetResourcesORN(resources))
+	}
 	return nil
 }
 
+//how do i know what value to compare against, since i will get both orn and rest api url, but how do i know whether to compare url or the orns with the .tf config file
```
Comment (pranav-okta) [inline okta/resource_okta_resource_set.go]: Please remove this comment.

**Review by pranav-okta — CHANGES_REQUESTED** [review]

File: okta/resource_okta_resource_set.go [hunk 5]
```diff
@@ -225,3 +277,11 @@ func removeResourcesFromResourceSet(ctx context.Context, client *sdk.APISuppleme
 	}
 	return nil
 }
+
```
Comment (pranav-okta) [inline okta/resource_okta_resource_set.go:282]: Please use [url.QueryUnescape](https://pkg.go.dev/net/url#QueryUnescape) and [url.QueryEscape](https://pkg.go.dev/net/url#QueryEscape).

**Review by pranav-okta — CHANGES_REQUESTED** [review]
Please use the built-in functions to escape or unescape the URL strings. Replacing the strings for every encoding character is not the best practice.

**Review by pranav-okta — APPROVED** [review]
