### PR TITLE
fix: add source to `data_source_okta_groups`

### LINKED ISSUE #2393: okta.data.okta_groups no longer returns source field
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
        Before submitting a bug report, we ask that you first [search existing issues](https://github.com/okta/terraform-provider-okta/issues) and [pull requests](https://github.com/okta/terraform-provider-okta/pulls) to see if someone else may have experienced the same issue or may have already submitted a fix for it. This helps to keep all relevant information in one place, including any potential workarounds.

### A Note on Terraform Core Issues

We also ask that you consider whether your issue may be related to Terraform Core. If you are running into one of the following scenarios, we recommend [opening an issue](https://github.com/hashicorp/terraform/issues/new/choose) in the Terraform Core repository instead:

* [Configuration Language](https://developer.hashicorp.com/terraform/language) or resource ordering issues
* [State](https://developer.hashicorp.com/terraform/language/state) and [State Backend](https://developer.hashicorp.com/terraform/language/backend) issues
* [Provisioner](https://developer.hashicorp.com/terraform/language/resources/provisioners/syntax) issues
* [Registry](https://registry.terraform.io/) issues
* Issues that span resources across multiple providers

### Terraform Version & Okta Provider Version(s)

Terraform v1.11.4
on darwin_arm64
+ provider registry.terraform.io/providers/okta/okta/ v5.1.0

### Affected Resource(s)

okta.data.okta_groups

### Can this be done in the Admin UI?

No

### Can this be done in the actual API call?

Yes

### Customer Information

Organization Name: <your-org-name>
Paid Customer: <yes/no>

### Terraform Configuration

```tf

output "groups_found" {
  value = data.okta_groups.foo
}

data "okta_groups" "foo" {
  search = "profile.name sw \"FOO \""
}

```

### Debug Output

```
~ source                    = "0oa10rgpmv7FOO" -> ""
```

### Expected Behavior

The source field has data

### Actual Behavior

The source field no longer has data

### Steps to reproduce

1. `terraform plan`

### Important Factoids

Running this with terraform provider pinned to 4.20.0 works as expected (no changes to output)

### References

_No response_

### PR DESCRIPTION
**Pull request by pranav-okta**
Fixes: #2393 

This is due to the removal of `additionalProperties` in [this](https://github.com/okta/terraform-provider-okta/pull/2328/files#diff-2c0890d421f05dd3df2f2fb55b6440954e41f9bbccec8fabd5900a63cc85086dL153) PR. Since the `source` is present in `additionalProperties`, the source is set to an empty string.

### CODE REVIEW

File: okta/services/idaas/data_source_okta_groups.go [hunk 1]
```diff
@@ -150,6 +150,14 @@ func dataSourceGroupsRead(ctx context.Context, d *schema.ResourceData, meta inte
 		arr[i]["type"] = okta_groups[i].Type
 		arr[i]["description"] = okta_groups[i].Profile.Description
 
+		additionalProperties := okta_groups[i].AdditionalProperties
+		src, ok := additionalProperties["source"].(map[string]any)
```
Comment (dhiwakar-okta) [inline okta/services/idaas/data_source_okta_groups.go:154]: Do we need to account for this in our VCR acceptance tests ? If yes, do they need to be re-recorded ?

**Review by dhiwakar-okta — DISMISSED** [review]

File: okta/services/idaas/data_source_okta_groups.go (hunk 1 above)
Comment (pranav-okta) [reply okta/services/idaas/data_source_okta_groups.go:154]: Currently, we don't have a test setup to add or import from AD, LDAP or agents.

**Review by dhiwakar-okta — APPROVED** [review]
