### PR TITLE
keep the network exclude order

### LINKED ISSUE #1185: Excluded Networks Order in `okta_threat_insight_settings`
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```sh
Terraform v1.0.3
on darwin_amd64
+ provider registry.terraform.io/okta/okta v3.30.0
```

### Affected Resource(s)

- okta_threat_insight_settings

### Terraform Configuration Files

```hcl
resource "okta_network_zone" "networks" {
  count =  20
  name     = "Network ${count.index}"
  type     = "IP"
  gateways = ["0.0.0.${count.index}/32"]
}

resource "okta_threat_insight_settings" "default" {
  action = "block"
  network_excludes = okta_network_zone.networks.*.id
}

```

### Expected Behavior

1. First terraform apply => resources created
2. Next terraform applies => no changes

### Actual Behavior

1. First terraform apply => resources created
2. Next terraform applies =>

```hcl
Terraform will perform the following actions:

  # okta_threat_insight_settings.default will be updated in-place
  ~ resource "okta_threat_insight_settings" "default" {
        id               = "threat_insight_settings"
      ~ network_excludes = [
          - "nzo3zr64xxyFfNE801d7",
            "nzo3zr16zx5GtVUXb1d7",
          + "nzo3zqx61sw2fx5Nx1d7",
          + "nzo3zqx61rXpQZ79u1d7",
            "nzo3zr12wbFzgb0QF1d7",
          - "nzo3zqz69vBn0QHDL1d7",
          + "nzo3zr0q4g36H4yaF1d7",
          + "nzo3zqz5oteAfPkv31d7",
          + "nzo3zqvtc5HmxBidn1d7",
            "nzo3zr7832tnRgncD1d7",
          - "nzo3zqz8jlBq2WK7j1d7",
          - "nzo3zqvovvGR1yH7t1d7",
          - "nzo3zr40eqbhSfRQ71d7",
          - "nzo3zr5vj9scJxFpu1d7",
          - "nzo3zqx61rXpQZ79u1d7",
            "nzo3zr4cuh3nZNJLr1d7",
          - "nzo3zr5oin7TXysJm1d7",
          - "nzo3zqz5oteAfPkv31d7",
          - "nzo3zqx61sw2fx5Nx1d7",
          + "nzo3zr1aixdIwdx8u1d7",
            "nzo3zr3rx6XQdY7su1d7",
          + "nzo3zqz69vBn0QHDL1d7",
          + "nzo3zr5vj9scJxFpu1d7",
          + "nzo3zr64xxyFfNE801d7",
          + "nzo3zr40eqbhSfRQ71d7",
          + "nzo3zr5oin7TXysJm1d7",
            "nzo3zr68ra5779H0d1d7",
          - "nzo3zqvtc5HmxBidn1d7",
          + "nzo3zqz8jlBq2WK7j1d7",
          + "nzo3zqvovvGR1yH7t1d7",
            "nzo3zr5vj8n9ZUT8T1d7",
          - "nzo3zr0q4g36H4yaF1d7",
          - "nzo3zr1aixdIwdx8u1d7",
        ]
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Basically, the resources will always be reordered in the plan.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### LINKED ISSUE #1221: ThreatInsight Configuration Continuously Reordering
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform 1.1.5
Okta Provider v3.31.0

### Affected Resource(s)

- okta_threat_insight_settings

### Terraform Configuration Files

```hcl
resource "okta_threat_insight_settings" "threat_insight" {
  action = "block"
  network_excludes = [
    okta_network_zone.dummy1.id,
    okta_network_zone.dummy2.id,
    okta_network_zone.dummy3.id,
    okta_network_zone.dummy4.id,
    okta_network_zone.dummy5.id,
    okta_network_zone.dummy6.id,
    okta_network_zone.dummy7.id,
    okta_network_zone.dummy8.id,
    okta_network_zone.dummy9.id
  ]
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

We recently added the threat insight resource to our okta configuration. Since adding this, we've noticed that every single terraform plan has a re-application of the settings where no change is made to the settings except for potentially some reordering of the network zones. These settings had values set prior to adding to terraform, but we did not import the resource before adding as we assumed it would just overwrite (given there's only one threat insight setting per instance).

Ideally, we would only see the threatinsight resource in each successive plan/apply if we added/removed network zones - as is, we see the same set of network_exclusions in every new plan.

### Actual Behavior

Threat insight settings are modified on every plan following addition to TF. Similar to the below (example, not actual output to avoid exposing networkIds):
```
  # okta_threat_insight_settings.threat_insight will be updated in-place
  ~ resource "okta_threat_insight_settings" "threat_insight" {
        id               = "threat_insight_settings"
      ~ network_excludes = [
            "networkid",
          - "networkid",
          - "networkid",
          - "networkid",
          + "networkid",
          + "networkid",
            "networkid",
          + "networkid",
          - "networkid",
        ]
        # (1 unchanged attribute hidden)
    }
```

### Steps to Reproduce

1. Add a bunch of network zone exclusions to threatinsight in the UI
2. Create and apply the threat insight configuration in terraform
3. See reordering of network zones on every future TF plan

### Important Factoids

We are running in OIE, if that matters.

### PR DESCRIPTION
**Pull request by duytiennguyen-okta**
Fix for ThreatInsight Configuration Continuously Reordering #1221
Closes #1221

Also fixes #1185

### CODE REVIEW

File: okta/resource_okta_threat_insight_settings.go [hunk 1]
```diff
@@ -27,6 +30,42 @@ func resourceThreatInsightSettings() *schema.Resource {
 				Optional:    true,
 				Description: "List of Network Zone IDs to exclude to be not logged or blocked by Okta ThreatInsight and proceed to Sign On rules evaluation",
 				Elem:        &schema.Schema{Type: schema.TypeString},
+				DiffSuppressFunc: func(k, old, new string, d *schema.ResourceData) bool {
+					// k will be "network_excludes.#"", "network_excludes.1", ..., "network_excludes.N"
+					items := strings.Split(k, ".")
+					// special case before the resource has been created
+					if old == "" || (len(items) > 1 && items[1] == "#") {
```
Comment (monde) [inline okta/resource_okta_threat_insight_settings.go]: I think we can get rid of the `items := strings.Split(k, ".")` line and keep the conditional small
`if old == "" || "network_excludes.#" {`

**Review by monde — CHANGES_REQUESTED** [review]

**Review by monde — APPROVED** [review]
