### PR TITLE
fixed app_group_assignments import

### LINKED ISSUE #628: okta_app_group_assignments import fails
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.5
on darwin_amd64
\+ provider registry.terraform.io/okta/okta v3.13.8
### Affected Resource(s)

- okta_app_group_assignments

### Terraform Configuration Files

```hcl
resource "okta_group" "ffm-qs-testers" {
  name        = "FFM-FM QuickSight Testers"
  description = "FFM-FM QuickSight Testers"

  lifecycle {
    ignore_changes = [
      users
    ]
  }
}

resource "okta_group" "ffm-qs-users" {
  name        = "FFM-FM QuickSight Users"
  description = "FFM-FM QuickSight Users"

  lifecycle {
    ignore_changes = [
      users
    ]
  }
}

resource "okta_app_saml" "ffm-qs" {
  preconfigured_app   = "amazon_aws"
  label               = "FFM-FM QuickSight"
  default_relay_state = "https://quicksight.aws.amazon.com/sn/start"

  groups = [okta_group.ffm-qs-testers.id, okta_group.ffm-qs-users.id]

  lifecycle {
    ignore_changes = [
      users, groups
    ]
  }
}

resource "okta_app_group_assignments" "ffm-qs" {
  app_id   = okta_app_saml.ffm-qs.id

  group {
    id = okta_group.ffm-qs-users.id
    priority = 1
  }

  group {
    id = okta_group.ffm-qs-testers.id
    priority = 2
  }
}
```

### Debug Output

https://gist.github.com/phi1ipp/8f0544bf8d92b90b14a8b4a068e86fe9
### Expected Behavior

resource imported
### Actual Behavior
error message
`Error: failed to fetch group assignments: the API returned an error: Not found: Resource not found: groups (AppInstance)`

### Steps to Reproduce

1. `terraform import okta_app_group_assignments.ffm-qs 0oa8v9m969rrbxJ96297`

### PR DESCRIPTION
**Pull request by phi1ipp**
Added missing importer for resourceAppGroupAssignments

### CODE REVIEW

File: okta/resource_okta_app_group_assignments.go [hunk 1]
```diff
@@ -17,7 +17,38 @@ func resourceAppGroupAssignments() *schema.Resource {
 		ReadContext:   resourceAppGroupAssignmentsRead,
 		DeleteContext: resourceAppGroupAssignmentsDelete,
 		UpdateContext: resourceAppGroupAssignmentsUpdate,
-		Importer:      &schema.ResourceImporter{},
+		Importer: &schema.ResourceImporter{
```
Comment (bogdanprodan-okta) [inline okta/resource_okta_app_group_assignments.go:20]: I think it can be implemented even simpler:
```
Importer: &schema.ResourceImporter{
	StateContext: func(ctx context.Context, d *schema.ResourceData, m interface{}) ([]*schema.ResourceData, error) {
		_ = d.Set("app_id", d.Id())
		return []*schema.ResourceData{d}, nil
	},
},
```
The rest of the job will be done by `resourceAppGroupAssignmentsRead`

Comment (phi1ipp) [reply okta/resource_okta_app_group_assignments.go:20]: @bogdanprodan-okta , 
I'm not a pro in Go or Terraform, so I'll take whatever you say :) So do you want me to resubmit the PR? Or will you do it yourself?

Comment (bogdanprodan-okta) [reply okta/resource_okta_app_group_assignments.go:20]: Yeah, go ahead and change it. I'll approve and merge it asap.

**Comment by phi1ipp** [comment]
@bogdanprodan-okta , updated PR with the latest change based on your suggestion

**Review by bogdanprodan-okta — APPROVED** [review]
