### PR TITLE
GH 2389 | OKTA-1053164 | okta_app_signon_policy Reports Bogus Change During Import

### LINKED ISSUE #2389: okta_app_signon_policy import issue.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
        Before submitting a bug report, we ask that you first [search existing issues](https://github.com/okta/terraform-provider-okta/issues) and [pull requests](https://github.com/okta/terraform-provider-okta/pulls) to see if someone else may have experienced the same issue or may have already submitted a fix for it. This helps to keep all relevant information in one place, including any potential workarounds.

### A Note on Terraform Core Issues

We also ask that you consider whether your issue may be related to Terraform Core. If you are running into one of the following scenarios, we recommend [opening an issue](https://github.com/hashicorp/terraform/issues/new/choose) in the Terraform Core repository instead:

* [Configuration Language](https://developer.hashicorp.com/terraform/language) or resource ordering issues
* [State](https://developer.hashicorp.com/terraform/language/state) and [State Backend](https://developer.hashicorp.com/terraform/language/backend) issues
* [Provisioner](https://developer.hashicorp.com/terraform/language/resources/provisioners/syntax) issues
* [Registry](https://registry.terraform.io/) issues
* Issues that span resources across multiple providers

### Terraform Version & Okta Provider Version(s)

OpenTofu v1.8.2
on <architecture>
+ provider registry.terraform.io/providers/okta/okta/ v5.0.0

### Affected Resource(s)

okta_app_signon_policy

### Can this be done in the Admin UI?

Yes

### Can this be done in the actual API call?

Unsure

### Customer Information

Organization Name: <your-org-name>
Paid Customer: <yes/no>

### Terraform Configuration

```
import {
    to = okta_app_signon_policy.app
    id = "rsxxxxxxxxxxxxxxxxx"
}

resource "okta_app_signon_policy" "app" {
  name = "app"
  description = ""
}
```

### Debug Output

NA

### Expected Behavior

There should not be any change during the import.

### Actual Behavior

There is always a change when the plan completes.

```
  # okta_app_signon_policy.app will be updated in-place
  # (imported from "rsxxxxxxxxxxxxxxxxx")
  ~ resource "okta_app_signon_policy" "app" {
      + catch_all       = false
        default_rule_id = "rsxxxxxxxxxxxxxxxxx"
        id              = "rsxxxxxxxxxxxxxxxxxr"
        name            = "app"
        priority        = 1
    }

Plan: 1 to import, 0 to add, 1 to change, 0 to destroy.
```

### Steps to reproduce

1. `terraform plan`

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by dhiwakar-okta**
Fixes [#2389](https://github.com/okta/terraform-provider-okta/issues/2389),  [#2404](https://github.com/okta/terraform-provider-okta/issues/2404)
We check if a resource is being imported and set CatchAll to true if it is.
If ID is set BUT Name & Description, the required fields are unset, then we know that the resource is being read in the context of an import.

### CODE REVIEW

File: okta/services/idaas/resource_okta_app_signon_policy.go [hunk 1]
```diff
@@ -182,6 +182,11 @@ func (r *appSignOnPolicyResource) Read(ctx context.Context, req resource.ReadReq
 		return
 	}
 
+	// When ID is set but required fields name, description aren't, it implies that the resource has been imported.
+	// The resource needn't be created from here on out, so the value for catch_all doesn't matter since it only has effect during Create
+	if !state.ID.IsNull() && state.Name.IsNull() && state.Description.IsNull() {
```
Comment (pranav-okta) [inline okta/services/idaas/resource_okta_app_signon_policy.go:187]: We have a test to check the imported resource. Is it not failing after this change?

**Review by pranav-okta — APPROVED** [review]

File: okta/services/idaas/resource_okta_app_signon_policy.go (hunk 1 above)
Comment (dhiwakar-okta) [reply okta/services/idaas/resource_okta_app_signon_policy.go:187]: In the import test case we don't check the value of catch_all.
catch_all isn't really returned by the API response, it is an attribute added to the schema purely for the purposes of managing Terraform and it only takes effect during Create, NOT Update, Read etc.

In TestAccResourceOktaAppSignOnPolicy_crud, check

`				ImportStateCheck: func(states []*terraform.InstanceState) error {
					if len(states) != 1 {
						return errors.New("failed to import schema into state")
					}
					instance := states[0]
					access := instance.Attributes["access"]
					if access != "ALLOW" {
						return fmt.Errorf("expected okta_app_signon_policy.test access to be set to ALLOW, got %s", access)
					}

					return nil
				},`
