### PR TITLE
OKTA-1015115 - Add `frontchannel_logout_uri` and `participate_slo` to the `okta_app_oauth` resource

### LINKED ISSUE #2162: Error Updating OAuth Application: Missing frontchannel_logout_uri When participate_slo is True
Description:

We encountered an issue while using the Terraform Okta Plugin to update an OAuth application. The error occurs because frontchannel_logout_uri is missing when participate_slo is set to true.

Error Message:

Error: failed to update OAuth application: the API returned an error: Api validation failed: frontchannel_logout_uri. Causes: errorSummary: frontchannel_logout_uri: ''frontchannel_logout_uri'' is required when ''participate_slo'' is true.

Steps to Reproduce:

1. Set up an OAuth application in Okta using UI. 
2. Configure `frontchannel_logout_uri` in the Terraform File. 
3. Attempt to apply the Terraform configuration. We get an error:
An argument named "frontchannel_logout_uri" is not expected here.

Expected Behavior:

The application should update successfully without requiring `frontchannel_logout_uri` unless specifically needed.

Actual Behavior:

The update fails with an API validation error, indicating that `frontchannel_logout_uri` is required when `participate_slo` is true.

Environment:

Terraform Enterprise Version: 1.9.5
Okta Plugin Version:4.11

### PR DESCRIPTION
**Pull request by pranav-okta**
Fixes: https://github.com/okta/terraform-provider-okta/issues/2162

Since we are using the newer SDK to create applications, all the VCR tests that call the application API failed. This PR includes the test fixes.

### CODE REVIEW

**Review by aditya-okta — DISMISSED** [review]

File: okta/services/idaas/resource_okta_app_oauth.go [hunk 1]
```diff
@@ -448,138 +464,198 @@ var groupsClaimResource = &schema.Resource{
...
 	}
 
-	raw, ok := d.GetOk("groups_claim")
-	if !ok {
+	// For now, keep the old behavior but with warnings
+	// TODO: Remove in future version - functionality temporarily maintained for backward compatibility
+	apiSupplement := getAPISupplementFromMetadata(meta)
+	appID := d.Id()
+
+	groupsClaim := raw.([]interface{})[0].(map[string]interface{})
```
Comment (dhiwakar-okta) [inline okta/services/idaas/resource_okta_app_oauth.go:535]: You might want to check the length here so we don't run into some sort of out of bounds exception, right ?

File: okta/services/idaas/resource_okta_app_oauth.go [hunk 2]
```diff
@@ -448,138 +464,198 @@ var groupsClaimResource = &schema.Resource{
...
 		Value: groupsClaim["value"].(string),
 	}
-	if d.Get("issuer_mode") != nil {
-		gc.IssuerMode = d.Get("issuer_mode").(string)
-	}
-	gct := groupsClaim["type"].(string)
-	if gct == "FILTER" {
+
+	// Map Terraform 'type' to API 'valueType'
+	claimType := groupsClaim["type"].(string)
```
Comment (dhiwakar-okta) [inline okta/services/idaas/resource_okta_app_oauth.go:565]: There really isn't any need to assign the value to another variable here, right ?
This isn't a big deal here TBH

File: okta/services/idaas/resource_okta_app_oauth.go [hunk 3]
```diff
@@ -448,138 +464,198 @@ var groupsClaimResource = &schema.Resource{
...
+		_ = d.Set("auto_key_rotation", oauthClient.GetAutoKeyRotation())
+		_ = d.Set("pkce_required", oauthClient.GetPkceRequired())
 	}
-	err = setAppSettings(d, app.Settings.App)
-	if err != nil {
-		return diag.Errorf("failed to set OAuth application settings: %v", err)
+
+	// Handle app settings from AdditionalProperties
+	if len(settings.AdditionalProperties) > 0 {
+		appSettingsJSON, _ := json.Marshal(settings.AdditionalProperties)
```
Comment (dhiwakar-okta) [inline okta/services/idaas/resource_okta_app_oauth.go:654]: You don't need to check err in case json.Marshal fails ?

File: okta/services/idaas/resource_okta_app_oauth.go [hunk 4]
```diff
@@ -796,141 +875,215 @@ func buildAppOAuth(d *schema.ResourceData, isNew bool) *sdk.OpenIdConnectApplica
...
+
+	// Handle JWKS if provided
+	if jwksList, ok := d.GetOk("jwks"); ok {
+		jwksData := jwksList.([]interface{})
+		if len(jwksData) > 0 {
+			// For now, temporarily disable inline JWKS due to v6 SDK schema conflicts
+			// This is a known limitation with the v6 SDK JWKS unmarshalling
+			// Users should use jwks_uri instead for v6 SDK compatibility
+			
+			// TODO: Re-enable when v6 SDK JWKS schema conflict is resolved
```
Comment (dhiwakar-okta) [inline okta/services/idaas/resource_okta_app_oauth.go:1000]: Can we remove these commented lines ?

File: okta/services/idaas/resource_okta_app_oauth.go [hunk 5]
```diff
@@ -796,141 +875,215 @@ func buildAppOAuth(d *schema.ResourceData, isNew bool) *sdk.OpenIdConnectApplica
...
-		refresh.LeewayPtr = utils.Int64Ptr(leeway.(int))
-	} else {
-		refresh.LeewayPtr = utils.Int64Ptr(0)
+	if hasRefresh {
+		refresh := v6okta.NewOpenIdConnectApplicationSettingsRefreshTokenWithDefaults()
+		if rotate, ok := d.GetOk("refresh_token_rotation"); ok {
+			refresh.SetRotationType(rotate.(string))
+		}
+		if leeway, ok := d.GetOk("refresh_token_leeway"); ok {
+			refresh.SetLeeway(int32(leeway.(int)))
```
Comment (dhiwakar-okta) [inline okta/services/idaas/resource_okta_app_oauth.go:1058]: What if the user sets a non number value for refresh_token_leeway, could this panic ?

File: okta/services/idaas/resource_okta_app_oauth.go [hunk 6]
```diff
@@ -949,13 +1102,16 @@ func validateGrantTypes(d *schema.ResourceData) error {
...
 	raw, ok := d.GetOk("groups_claim")
 	if ok {
+		logger(meta).Warn("groups_claim is deprecated and will be removed in a future version. Please use Authorization Server Claims (okta_auth_server_claim) or app profile configuration instead.")
+
 		c := meta.(*config.Config)
 		if c.IsOAuth20Auth() {
 			logger(meta).Warn("groups_claim arguments are disabled with OAuth 2.0 API authentication")
 		} else {
-			groupsClaim := raw.(*schema.Set).List()[0].(map[string]interface{})
+			groupsClaim := raw.([]interface{})[0].(map[string]interface{})
```
Comment (dhiwakar-okta) [inline okta/services/idaas/resource_okta_app_oauth.go:1128]: Shouldn't you check the length first ?

File: okta/services/idaas/resource_okta_app_oauth.go [hunk 7]
```diff
@@ -1004,10 +1160,74 @@ func validateAppOAuth(d *schema.ResourceData, meta interface{}) error {
...
+		hide.SetIOS(hideIOS.(bool))
+	}
+	if hideWeb, ok := d.GetOk("hide_web"); ok {
+		hide.SetWeb(hideWeb.(bool))
+	}
+	visibility.SetHide(*hide)
+
+	if appLinks, ok := d.GetOk("app_links_json"); ok {
+		var links map[string]bool
+		_ = json.Unmarshal([]byte(appLinks.(string)), &links)
```
Comment (dhiwakar-okta) [inline okta/services/idaas/resource_okta_app_oauth.go]: Should you be checking the error here ? 
This is a JSON string

File: okta/services/idaas/resource_okta_app_oauth_test.go [hunk 8]
```diff
@@ -44,10 +41,12 @@ func TestAccResourceOktaAppOauth_basic(t *testing.T) {
 					resource.TestCheckResourceAttr(resourceName, "auto_submit_toolbar", "false"),
 					resource.TestCheckResourceAttr(resourceName, "redirect_uris.#", "1"),
 					resource.TestCheckResourceAttr(resourceName, "response_types.#", "1"),
-					resource.TestCheckResourceAttr(resourceName, "client_secret", "something_from_somewhere"),
-					resource.TestCheckResourceAttr(resourceName, "client_id", "something_from_somewhere"),
+					resource.TestCheckResourceAttrSet(resourceName, "client_secret"),
```
Comment (dhiwakar-okta) [inline okta/services/idaas/resource_okta_app_oauth_test.go:44]: Didn't you remove these from these from the *.tf files for resources too ?

File: okta/services/idaas/resource_okta_app_oauth_test.go [hunk 9]
```diff
@@ -321,34 +324,42 @@ func TestAccResourceOktaAppOauth_serviceWithJWKSURI(t *testing.T) {
...
 					resource.TestCheckResourceAttr(resourceName, "jwks_uri", "https://example.com"),
 				),
 			},
 		},
 	})
 }
 
-func createDoesAppExist(app sdk.App) func(string) (bool, error) {
+// createDoesAppExist is a compatibility wrapper for other test files
+func createDoesAppExist(app interface{}) func(string) (bool, error) {
```
Comment (dhiwakar-okta) [inline okta/services/idaas/resource_okta_app_oauth_test.go:341]: Is this being called anywhere ?

**Review by dhiwakar-okta — DISMISSED** [review]
Approved with comments.

File: okta/services/idaas/resource_okta_app_oauth.go (hunk 5 above)
Comment (pranav-okta) [reply okta/services/idaas/resource_okta_app_oauth.go:1058]: If this is set as a non-integer, Terraform operations will complain since it is defined as `TypeInt`.

File: okta/services/idaas/resource_okta_app_oauth.go (hunk 4 above)
Comment (pranav-okta) [reply okta/services/idaas/resource_okta_app_oauth.go:1000]: This is related to the OAS spec bug, and we will need this once the spec is fixed.

File: okta/services/idaas/resource_okta_app_oauth_test.go (hunk 9 above)
Comment (pranav-okta) [reply okta/services/idaas/resource_okta_app_oauth_test.go:341]: Yes.

**Review by dhiwakar-okta — APPROVED** [review]
LGTM 🚀
