### PR TITLE
GH-2189 | OKTA-1087655 | Changes To Update Okta Default Brand's help_url

### LINKED ISSUE #2189: Unable to update Okta Default Brand's help_url
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_customized_signin_page

### Terraform Configuration Files

```hcl
data "okta_brands" "brands" {

}

data "okta_default_signin_page" "default_signin_page" {
  for_each = { for brand in data.okta_brands.brands.brands : brand.id => brand }

  brand_id = each.value.id
}

resource "okta_customized_signin_page" "customized_signin_page" {
  for_each = data.okta_default_signin_page.default_signin_page

  brand_id       = each.value.brand_id
  widget_version = each.value.widget_version
  page_content   = each.value.page_content

  widget_customizations {
    widget_generation = each.value.widget_customizations.widget_generation
    help_url          = "https://changeme.com"
  }
}
```

### Expected Behavior

Update help_url for all domains including the default domain.

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

 I don't know

### Actual Behavior

Error: failed to update customized sign in page (401 Forbidden) due to cannot update the brand's default page_content.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

None

### References

None

- #0000

### PR DESCRIPTION
**Pull request by dhiwakar-okta**
Fixes #2189 . Both `page_content` and `widget_version` are now optional fields since `page_content` cannot be set for Okta's default brand. `widget_version` is optional since it must NOT be specified if `page_content` isn't specified either.

### CODE REVIEW

File: okta/services/idaas/resource_okta_customized_signin_page.go [hunk 1]
```diff
@@ -40,6 +50,10 @@ func (r *customizedSigninPageResource) Configure(_ context.Context, req resource
 }
 
 func (r *customizedSigninPageResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
+
+	oktaMutexKV.Lock(resources.OktaIDaaSCustomizedSignInPage)
```
Comment (aditya-okta) [inline okta/services/idaas/resource_okta_customized_signin_page.go:54]: why is locking required?

File: okta/services/idaas/customization.go [hunk 2]
```diff
@@ -111,40 +111,42 @@ func mapSignInPageToState(ctx context.Context, data *okta.SignInPage, state *sig
...
 	sp := okta.SignInPage{}
-	sp.SetPageContent(model.PageContent.ValueString())
-	sp.SetWidgetVersion(model.WidgetVersion.ValueString())
+	if !model.PageContent.IsNull() {
+		sp.SetPageContent(model.PageContent.ValueString())
+	}
 
 	if !model.WidgetVersion.IsNull() {
-		wc := okta.SignInPageAllOfWidgetCustomizations{}
-		wcm := &widgetCustomizationsModel{}
```
Comment (aditya-okta) [inline okta/services/idaas/customization.go:119]: why have we moved this out of the if block?

**Review by aditya-okta — APPROVED** [review]
approved with comments

File: okta/services/idaas/resource_okta_customized_signin_page.go (hunk 1 above)
Comment (dhiwakar-okta) [reply okta/services/idaas/resource_okta_customized_signin_page.go:54]: Because when I had multiple instances of this resource defined in my Terraform configuration file, a panic occurred 

```
=== RUN   TestAccResourceOktaCustomizedSignInPage_crud
=== VCR PLAY CASSETTE "oie-00" for TestAccResourceOktaCustomizedSignInPage_crud
fatal error: concurrent map writes

goroutine 414687 [running]:
internal/runtime/maps.fatal({0x390e95d?, 0x33eac40?})
	/opt/hostedtoolcache/go/1.24.7/x64/src/runtime/panic.go:1058 +0x18
github.com/okta/terraform-provider-okta/okta/services/idaas.(*customizedSigninPageResource).Schema(0x3da4508?, {0xc00067ec60?, 0x38f98df?}, {}, 0xc00663d320)
	/home/runner/work/terraform-provider-okta/terraform-provider-okta/okta/services/idaas/resource_okta_customized_signin_page.go:41 +0x273
```

File: okta/services/idaas/customization.go (hunk 2 above)
Comment (dhiwakar-okta) [reply okta/services/idaas/customization.go:119]: With this PR the attributes page_content & widget_version are now optional (since the default Brand doesn't allow page_content to be defined, it must not be provided any value i.e. it is not required). Given this fact, the condition doesn't make sense as fields like HelpUrl, HelpLabel etc can be defined even if WidgetVersion is null, which is why it had to be moved out of that condition.
