### PR TITLE
GH-2495 | OKTA-1036924 | "dns_records" Empty in Data Source "okta_domain"

### LINKED ISSUE #2495: dns_records empty in data "okta_domain"
### Community Note

When using the data "okta_domain" data source, the dns_records attribute always returns an empty list, even though the domain was originally created via Terraform and the DNS records exist in the okta_domain resource.

data "okta_domain" "domain" {
    certificate_source_type = "OKTA_MANAGED"
    dns_records             = []
    domain                  = "XXXXXX"
    domain_id_or_name       = "XXXXXXX"
    id                      = "XXXXXX"
    validation_status       = "COMPLETED"
}

### Terraform Version & Okta Provider Version(s)

Terraform v1.10.0
on <architecture>
+ provider registry.terraform.io/providers/okta/okta/ v6.1.0

### Affected Resource(s)

okta_domain

### Can this be done in the Admin UI?

Yes

### Can this be done in the actual API call?

Yes

### Customer Information

Organization Name: trial-4966343.okta.com
Paid Customer: no

### Terraform Configuration

```tf
data "okta_domain" "domain" {
  domain_id_or_name = var.okta_custom_domain

  depends_on = [okta_domain.domain]
}
```

### Debug Output

https://gist.github.com/minoli-yl/b9fd1c794b80107d08d30883e78e9dbe.js

### Expected Behavior

```
"dnsRecords": [
{
"expiration": "string",
"fqdn": "_oktaverification.login.example.com",
"recordType": "TXT",
"values": []
}
],
```

### Actual Behavior

`    dns_records             = []
`

### Steps to reproduce

1. `terraform apply`

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by dhiwakar-okta**
Fixes #2495 
Additionally, I've updated the resource and datasource to use the latest version of the SDK v5. 
The VCR tests have been regenerated

### CODE REVIEW

File: okta/services/idaas/data_source_okta_domain.go [hunk 1]
```diff
@@ -86,41 +86,46 @@ func dataSourceDomainRead(ctx context.Context, d *schema.ResourceData, meta inte
...
 
-	d.SetId(domain.Id)
+	d.SetId(domain.GetId())
 	d.Set("domain", domain.Domain)
 	d.Set("validation_status", domain.ValidationStatus)
 	d.Set("certificate_source_type", domain.CertificateSourceType)
-	arr := make([]map[string]interface{}, len(domain.DnsRecords))
-	for i := range domain.DnsRecords {
+	// retrieve DNS records by calling api/v1/domains/{domainId}
+	_domain, _, err := getOktaV5ClientFromMetadata(meta).CustomDomainAPI.GetCustomDomain(ctx, domainID).Execute()
```
Comment (aditya-okta) [inline okta/services/idaas/data_source_okta_domain.go]: why are we using "_domain" and not "domain" ?

**Review by aditya-okta — CHANGES_REQUESTED** [review]

File: okta/services/idaas/data_source_okta_domain.go (hunk 1 above)
Comment (dhiwakar-okta) [reply okta/services/idaas/data_source_okta_domain.go]: I didn't want to shadow or replace domain as is since the current code flow fetched information from ListDomains.
_domain would pretty much contain the same information as domain except that _domain also has the dnsRecords field populated. It would be more efficient to use domain directly, let me make the code changes for that.

**Review by aditya-okta — APPROVED** [review]
LGTM
